### ISSUE TITLE
[Issue] scan node did not point to correct position

### ISSUE THREAD

**Issue by CoolLKKPS** [LethalCompanyModding/LCUltrawide#5]
same as topic

**Comment by CoolLKKPS** [comment]
might also need to install `FixCameraResolution v1.2.2 by Rumi`

**Comment by RobynLlama** [comment]
The only time I've heard of this issue was when somebody was also using another mod that messes with render settings like HDLC. If FixCameraResolution also messes with render settings then I imagine you'll just have to pick one of the two and stick with it


Looks like FixCameraResolution modifies both the render settings and scan node location

From the changelog: 

### 1.0.2
- Scan node location bug fix

**Comment by CoolLKKPS** [comment]
ok thx, i don't have time close this issue for now, u can close this issue ticket
